### ISSUE TITLE
Map tasks

### ISSUE THREAD

**Issue by mauriciabad** [socialworldpes/PetWorld-Android#12]
# Tasks
- [x] Button "search here" when map is moved.
- [ ] Custom marker images.
- [ ] View Walks.
- [ ] View Routes.
- [ ] Only show Meetings and Walks that are in the future.
