### ISSUE TITLE
Add Fab Button

### ISSUE THREAD

**Issue by mauriciabad** [socialworldpes/PetWorld-Android#14]
# Tasks
- [x] Fab Button
- [x] Small Fab Buttons
  - [x] Meeting
  - [x] Walk
  - [x] Route
- [x] Each one opens a new Activity
- [x] Open buttons when map is long pressed and pass location information
