### ISSUE TITLE
Fill Meetings RecyclerView

### ISSUE THREAD

**Issue by mauriciabad** [socialworldpes/PetWorld-Android#15]
# Tasks
- [ ] Fill meetings RecyclerView
- [ ] Change RecyclerView when tab is changed
- [ ] Sort meetings by date or distance (chose the best)
